// src/react/AgentReadyWidget.tsx
import { useEffect, useMemo, useState } from "react";
import type { ReadinessReport, WidgetColors, WidgetPosition, WidgetTheme } from "../client/types.js";
import { useAgentReadyStatus } from "./useAgentReadyStatus.js";
import { useAgentReadyReadiness } from "./useAgentReadyReadiness.js";

export type AgentReadyWidgetProps = {
  /**
   * Endpoint base URL used to fetch /llms-status and /llms-readiness.
   * In Convex setups this is typically `*.convex.site`. Required.
   */
  appUrl: string;
  /**
   * Optional public app URL used for visible file links and AI chat prompts.
   * Set this when your production frontend lives on a different domain (custom domain,
   * Vercel, Netlify, Cloudflare Pages) than the endpoint base. When omitted, the widget
   * uses status.appUrl from the component, then window.location.origin, then appUrl.
   */
  publicAppUrl?: string;
  position?: WidgetPosition;
  theme?: WidgetTheme;
  /**
   * Hide the entire widget while keeping generated files and routes active.
   * Resolves from prop, then config (`widgetVisible`), then `true`.
   */
  visible?: boolean;
  showTestModeBadge?: boolean;
  showStatus?: boolean;
  showFiles?: boolean;
  showAppName?: boolean;
  showDescription?: boolean;
  showMeta?: boolean;
  colors?: Partial<WidgetColors>;
  llmsTxtPath?: string;
  agentsMdPath?: string;
  fullTxtPath?: string;
  statusPath?: string;
  readinessPath?: string;
  rssFeedPath?: string;
  showScoreTab?: boolean;
  cleanMode?: boolean;
  showHumanTab?: boolean;
  showMachineTab?: boolean;
  showChatLinks?: boolean;
  showChatGPT?: boolean;
  showClaude?: boolean;
  showPerplexity?: boolean;
  /**
   * Enable the mobile collapsed presentation. When true, viewports below
   * `mobileBreakpoint` show a compact tab row with a caret toggle.
   * Default: true.
   */
  mobileCollapse?: boolean;
  /**
   * Pixel width below which the widget runs in mobile mode.
   * Default: 480.
   */
  mobileBreakpoint?: number;
  /**
   * Initial collapsed state on mobile. Default: true.
   */
  defaultMobileCollapsed?: boolean;
  /**
   * Enable the collapsed presentation on desktop too. When true, the widget shows
   * the caret toggle on desktop viewports and starts collapsed by default.
   * Width and insets remain at their full desktop values.
   * Resolves from prop, then config (`widgetDesktopCollapse`), then `true`.
   */
  desktopCollapse?: boolean;
};

// Trim trailing slash so we never produce double-slash URLs.
function normalizeBase(value: string | null | undefined): string {
  if (!value) return "";
  return value.replace(/\/+$/, "");
}

// Compare two URLs by host. Returns true when both parse and have the same host.
function sameHost(a: string, b: string): boolean {
  try {
    return new URL(a).host === new URL(b).host;
  } catch {
    return false;
  }
}

type Tab = "HUMAN" | "MACHINE" | "SCORE";

// Inline Phosphor ArrowSquareOut icon (16x16, regular weight).
function ArrowSquareOutIcon({ color = "currentColor" }: { color?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={14}
      height={14}
      viewBox="0 0 256 256"
      fill={color}
      style={{ flexShrink: 0 }}
    >
      <path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z" />
    </svg>
  );
}

// Inline Phosphor CaretDown / CaretUp icon for the mobile expand toggle.
function CaretIcon({ direction, color = "currentColor" }: { direction: "up" | "down"; color?: string }) {
  const path =
    direction === "down"
      ? "M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
      : "M213.66,165.66a8,8,0,0,1-11.32,0L128,91.31,53.66,165.66a8,8,0,0,1-11.32-11.32l80-80a8,8,0,0,1,11.32,0l80,80A8,8,0,0,1,213.66,165.66Z";
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={14}
      height={14}
      viewBox="0 0 256 256"
      fill={color}
      style={{ flexShrink: 0 }}
    >
      <path d={path} />
    </svg>
  );
}

// Track viewport width via matchMedia. Returns false on the server.
function useIsMobile(breakpoint: number): boolean {
  const [isMobile, setIsMobile] = useState<boolean>(false);
  useEffect(() => {
    if (typeof window === "undefined" || !window.matchMedia) return;
    const mql = window.matchMedia(`(max-width: ${breakpoint}px)`);
    setIsMobile(mql.matches);
    const handler = (event: MediaQueryListEvent) => setIsMobile(event.matches);
    if (mql.addEventListener) {
      mql.addEventListener("change", handler);
      return () => mql.removeEventListener("change", handler);
    }
    // Safari < 14 fallback.
    mql.addListener(handler);
    return () => mql.removeListener(handler);
  }, [breakpoint]);
  return isMobile;
}

export function AgentReadyWidget(props: AgentReadyWidgetProps) {
  const position = props.position ?? "floating-bottom-right";
  const theme = props.theme ?? "system";
  const colors = props.colors ?? {};
  const llmsTxtPath = props.llmsTxtPath ?? "/llms.txt";
  const agentsMdPath = props.agentsMdPath ?? "/agents.md";
  const fullTxtPath = props.fullTxtPath ?? "/llms-full.txt";
  const statusPath = props.statusPath ?? "/llms-status";
  const readinessPath = props.readinessPath ?? "/llms-readiness";
  const rssFeedPath = props.rssFeedPath ?? "/feed.xml";

  const status = useAgentReadyStatus({ appUrl: props.appUrl, statusPath });
  const readiness = useAgentReadyReadiness({ appUrl: props.appUrl, readinessPath });

  // Props override config. When prop is undefined, fall back to status endpoint (config-driven).
  const widgetVisible = props.visible ?? status?.widgetVisible ?? true;
  const showStatus = props.showStatus ?? status?.widgetStatusVisible ?? true;
  const showFiles = props.showFiles ?? status?.widgetShowFiles ?? true;
  const showAppName = props.showAppName ?? status?.widgetShowAppName ?? true;
  const showDescription = props.showDescription ?? status?.widgetShowDescription ?? true;
  const showMeta = props.showMeta ?? status?.widgetShowMeta ?? true;
  const scoreTabVisible = props.showScoreTab ?? status?.widgetShowScoreTab ?? false;
  const cleanMode = props.cleanMode ?? status?.widgetCleanMode ?? false;
  const humanTabVisible = props.showHumanTab ?? status?.widgetShowHumanTab ?? true;
  const machineTabVisible = props.showMachineTab ?? status?.widgetShowMachineTab ?? true;
  const chatLinksVisible = props.showChatLinks ?? status?.widgetShowChatLinks ?? true;
  const chatGPTVisible = props.showChatGPT ?? status?.widgetShowChatGPT ?? true;
  const claudeVisible = props.showClaude ?? status?.widgetShowClaude ?? true;
  const perplexityVisible = props.showPerplexity ?? status?.widgetShowPerplexity ?? true;

  // Pick the first visible tab as default.
  const visibleTabs = [
    humanTabVisible && "HUMAN",
    machineTabVisible && "MACHINE",
    scoreTabVisible && "SCORE",
  ].filter(Boolean) as Tab[];

  const [tab, setTab] = useState<Tab>(visibleTabs[0] ?? "HUMAN");
  const [initialVersion, setInitialVersion] = useState<string | null>(null);

  // Mobile collapsed presentation. Defaults preserve existing behavior on desktop.
  const mobileCollapseEnabled = props.mobileCollapse ?? true;
  const mobileBreakpoint = props.mobileBreakpoint ?? 480;
  const defaultMobileCollapsed = props.defaultMobileCollapsed ?? true;
  const isMobile = useIsMobile(mobileBreakpoint);
  // mobileActive drives mobile-specific visuals (width clamp, edge insets, compact tabs).
  const mobileActive = isMobile && mobileCollapseEnabled;
  // desktopCollapseActive drives the same toggle UX on desktop without changing widget dimensions.
  const desktopCollapseEnabled = props.desktopCollapse ?? status?.widgetDesktopCollapse ?? true;
  const desktopCollapseActive = !isMobile && desktopCollapseEnabled;
  // collapseActive controls toggle button visibility and panel show/hide regardless of viewport.
  const collapseActive = mobileActive || desktopCollapseActive;
  const [collapsed, setCollapsed] = useState<boolean>(defaultMobileCollapsed);
  const showPanel = !collapseActive || !collapsed;

  useEffect(() => {
    if (status?.generatedFromVersion && initialVersion === null) {
      setInitialVersion(status.generatedFromVersion);
    }
  }, [status, initialVersion]);

  const isStale =
    !!status?.generatedFromVersion &&
    !!initialVersion &&
    status.generatedFromVersion !== initialVersion;

  // Endpoint base: where the widget fetches /llms-status and /llms-readiness.
  // Falls back to the browser origin when the prop is missing.
  const endpointBase = useMemo(() => {
    const raw = props.appUrl ?? (typeof window !== "undefined" ? window.location.origin : "");
    return normalizeBase(raw);
  }, [props.appUrl]);

  // Visible base: what humans and AI agents see in chat prompts and copy links.
  // Precedence: publicAppUrl prop, status.appUrl from the component, window.location.origin,
  // then the legacy appUrl prop. Apps that pass only appUrl keep working.
  const visibleBase = useMemo(() => {
    const fromProp = normalizeBase(props.publicAppUrl);
    if (fromProp) return fromProp;
    const fromStatus = normalizeBase(status?.appUrl ?? null);
    if (fromStatus) return fromStatus;
    if (typeof window !== "undefined") {
      return normalizeBase(window.location.origin);
    }
    return endpointBase;
  }, [props.publicAppUrl, status?.appUrl, endpointBase]);

  // Dev-only warning when the visible URL clearly disagrees with the browser origin
  // in a way that suggests a stale Convex `.site` URL leaked into a production bundle.
  // Quiet in production builds.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const isProd =
      typeof process !== "undefined" && process.env && process.env.NODE_ENV === "production";
    if (isProd) return;
    if (!visibleBase) return;
    const origin = window.location.origin;
    const isLocal = /(^http:\/\/localhost)|(^http:\/\/127\.0\.0\.1)|(^http:\/\/\[::1\])/.test(
      origin,
    );
    if (isLocal) return;
    if (sameHost(visibleBase, origin)) return;
    if (visibleBase.includes(".convex.site") && !origin.includes(".convex.site")) {
      console.warn(
        "[agent-ready] Widget visible URL points to a Convex .site URL while the browser is on a custom domain. " +
          "Set publicAppUrl on <AgentReadyWidget> or VITE_SITE_URL in your build to avoid leaking the dev URL.",
      );
    }
  }, [visibleBase]);

  const urls = useMemo(
    () => ({
      llmsTxt: `${visibleBase}${llmsTxtPath}`,
      agentsMd: `${visibleBase}${agentsMdPath}`,
      fullTxt: `${visibleBase}${fullTxtPath}`,
      rssFeed: `${visibleBase}${rssFeedPath}`,
      // Status link still points at the endpoint base because that is where the JSON lives.
      status: `${endpointBase}${statusPath}`,
    }),
    [visibleBase, endpointBase, llmsTxtPath, agentsMdPath, fullTxtPath, rssFeedPath, statusPath],
  );

  // Build AI chat URLs from the raw llms.txt URL.
  const chatLinks = useMemo(() => {
    const encoded = encodeURIComponent(urls.llmsTxt);
    return {
      chatgpt: `https://chatgpt.com/?hints=search&q=Read+this+URL+${encoded}+and+summarize+the+app`,
      claude: `https://claude.ai/new?q=Read+this+URL+${encoded}+and+summarize+the+app`,
      perplexity: `https://www.perplexity.ai/?q=Read+this+URL+${encoded}+and+summarize+the+app`,
    };
  }, [urls.llmsTxt]);

  const containerStyle = positionStyle(position, mobileActive);

  // Merge user hex colors into CSS custom properties.
  const colorVars: Record<string, string> = {};
  if (colors.bg) colorVars["--agent-ready-bg"] = colors.bg;
  if (colors.border) colorVars["--agent-ready-panel-border"] = colors.border;
  if (colors.textActive) colorVars["--agent-ready-text-active"] = colors.textActive;
  if (colors.textInactive) colorVars["--agent-ready-text-inactive"] = colors.textInactive;
  if (colors.tabActiveBg) colorVars["--agent-ready-tab-active-bg"] = colors.tabActiveBg;
  if (colors.accent) colorVars["--agent-ready-accent"] = colors.accent;

  // Hide widget entirely without affecting generated files or HTTP routes.
  if (!widgetVisible || visibleTabs.length === 0) return null;

  // Resolve effective app name / description visibility under clean mode.
  const effectiveShowAppName = cleanMode ? false : showAppName;
  const effectiveShowDescription = cleanMode ? false : showDescription;

  return (
    <div
      data-theme={theme}
      style={{
        ...containerStyle,
        ...colorVars,
        width: mobileActive ? "min(280px, calc(100vw - 24px))" : 280,
        maxWidth: mobileActive ? "calc(100vw - 24px)" : undefined,
        background: "var(--agent-ready-bg, #1a1a1a)",
        border: "1px solid var(--agent-ready-panel-border, #333333)",
        borderRadius: "var(--agent-ready-radius, 4px)",
        color: "var(--agent-ready-text-active, #e5e5e5)",
        fontFamily: "var(--agent-ready-font, 'Courier New', Courier, monospace)",
        fontSize: 12,
        letterSpacing: "0.1em",
        overflow: "hidden",
      }}
    >
      <div style={toggleRowStyle}>
        {humanTabVisible ? (
          <TabButton
            label="HUMAN"
            active={tab === "HUMAN"}
            onClick={() => setTab("HUMAN")}
            compact={collapseActive}
          />
        ) : null}
        {machineTabVisible ? (
          <TabButton
            label="MACHINE"
            active={tab === "MACHINE"}
            onClick={() => setTab("MACHINE")}
            compact={collapseActive}
          />
        ) : null}
        {scoreTabVisible ? (
          <TabButton
            label="SCORE"
            active={tab === "SCORE"}
            onClick={() => setTab("SCORE")}
            compact={collapseActive}
          />
        ) : null}
        {collapseActive ? (
          <button
            type="button"
            onClick={() => setCollapsed((prev) => !prev)}
            aria-expanded={!collapsed}
            aria-label={collapsed ? "Expand widget" : "Collapse widget"}
            style={mobileToggleButtonStyle}
          >
            <CaretIcon
              direction={collapsed ? "down" : "up"}
              color="var(--agent-ready-text-inactive, #888888)"
            />
          </button>
        ) : null}
      </div>

      {!showPanel ? null : tab === "SCORE" ? (
        <ScorePanel readiness={readiness} />
      ) : tab === "HUMAN" ? (
        <div style={panelStyle}>
          {effectiveShowAppName ? (
            <p style={paragraphStyle}>
              {status?.appName ?? "LLMs discovery"}
            </p>
          ) : null}
          {effectiveShowDescription ? (
            <p style={subParagraphStyle}>
              These files help AI agents understand this app.
            </p>
          ) : null}
          {showFiles ? (
            <>
              <CopyRow label="llms.txt" url={urls.llmsTxt} />
              <CopyRow label="agents.md" url={urls.agentsMd} />
              {status?.fullTxtEnabled ? <CopyRow label="llms-full.txt" url={urls.fullTxt} /> : null}
            </>
          ) : null}
          {chatLinksVisible ? (
            <>
              {(effectiveShowAppName || effectiveShowDescription || showFiles) ? <div style={dividerStyle} /> : null}
              {chatGPTVisible ? <ExternalLink label="Open in ChatGPT" url={chatLinks.chatgpt} /> : null}
              {claudeVisible ? <ExternalLink label="Open in Claude" url={chatLinks.claude} /> : null}
              {perplexityVisible ? <ExternalLink label="Open in Perplexity" url={chatLinks.perplexity} /> : null}
            </>
          ) : (
            (effectiveShowAppName || effectiveShowDescription || showFiles) ? null : null
          )}
        </div>
      ) : (
        <div style={panelStyle}>
          {props.showTestModeBadge !== false && status?.testMode ? (
            <TestModeBadge />
          ) : null}
          {isStale ? (
            <div style={staleBannerStyle} role="status" aria-live="polite">
              Content updated — refresh
            </div>
          ) : null}
          <FileRow label="llms.txt" url={urls.llmsTxt} />
          <FileRow label="agents.md" url={urls.agentsMd} />
          {status?.fullTxtEnabled ? <FileRow label="llms-full.txt" url={urls.fullTxt} /> : null}
          {status?.rssEnabled ? <FileRow label="feed.xml" url={urls.rssFeed} /> : null}
          {showStatus ? <FileRow label="status" url={urls.status} /> : null}
          {showMeta ? (
            <>
              <p style={metaStyle}>
                {status?.lastGeneratedAt
                  ? `generated ${new Date(status.lastGeneratedAt).toLocaleString()}`
                  : "not generated yet"}
              </p>
              {status?.generationInProgress ? <p style={metaStyle}>Generating...</p> : null}
              {status?.hasDrafts ? <p style={metaStyle}>Drafts pending</p> : null}
            </>
          ) : null}
        </div>
      )}
    </div>
  );
}

// --- Subcomponents ---

function TabButton(props: { label: string; active: boolean; onClick: () => void; compact?: boolean }) {
  return (
    <button
      type="button"
      onClick={props.onClick}
      style={{
        flex: 1,
        height: 40,
        minWidth: props.compact ? 0 : 100,
        background: props.active ? "var(--agent-ready-tab-active-bg, #2a2a2a)" : "#111111",
        color: props.active
          ? "var(--agent-ready-text-active, #e5e5e5)"
          : "var(--agent-ready-text-inactive, #666666)",
        fontFamily: "inherit",
        fontSize: "inherit",
        letterSpacing: "inherit",
        border: "none",
        borderBottom: "1px solid var(--agent-ready-panel-border, #333333)",
        fontWeight: props.active ? 600 : 400,
        cursor: "pointer",
        transition: "background 120ms ease",
      }}
    >
      {props.label}
    </button>
  );
}

/** HUMAN tab: copy-to-clipboard row for file URLs. */
function CopyRow(props: { label: string; url: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(props.url);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch {
      // Clipboard permission denied.
    }
  };
  return (
    <div style={rowStyle}>
      <a href={props.url} target="_blank" rel="noreferrer" style={linkStyle}>
        {props.label}
      </a>
      <button type="button" onClick={copy} style={copyButtonStyle}>
        {copied ? "copied" : "copy"}
      </button>
    </div>
  );
}

/** MACHINE tab: file link with an open-in-new-tab icon. */
function FileRow(props: { label: string; url: string }) {
  return (
    <div style={rowStyle}>
      <a href={props.url} target="_blank" rel="noreferrer" style={linkStyle}>
        {props.label}
      </a>
      <a
        href={props.url}
        target="_blank"
        rel="noreferrer"
        style={iconLinkStyle}
        title={`Open ${props.label}`}
      >
        <ArrowSquareOutIcon color="#888888" />
      </a>
    </div>
  );
}

/** HUMAN tab: external AI chat link with arrow icon. */
function ExternalLink(props: { label: string; url: string }) {
  return (
    <a
      href={props.url}
      target="_blank"
      rel="noreferrer"
      style={externalLinkStyle}
    >
      <span>{props.label}</span>
      <ArrowSquareOutIcon color="#888888" />
    </a>
  );
}

/** SCORE tab: readiness score, colored dot, check list. */
function ScorePanel(props: { readiness: ReadinessReport | null }) {
  const { readiness } = props;
  if (!readiness) {
    return (
      <div style={panelStyle}>
        <p style={{ ...metaStyle, margin: 0 }}>Loading readiness...</p>
      </div>
    );
  }

  const { score, checks } = readiness;
  const dotColor = score >= 80 ? "#22c55e" : score >= 50 ? "#eab308" : "#ef4444";

  return (
    <div style={panelStyle}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
        <span
          style={{
            width: 10,
            height: 10,
            borderRadius: "50%",
            background: dotColor,
            flexShrink: 0,
          }}
        />
        <span
          style={{
            fontFamily: "'Courier New', Courier, monospace",
            fontSize: 24,
            fontWeight: 700,
            lineHeight: 1,
          }}
        >
          {score}
        </span>
        <span style={{ color: "#888888", fontSize: 11 }}>/100</span>
      </div>

      <div style={dividerStyle} />

      {checks.map((check) => (
        <div key={check.id} style={scoreCheckRowStyle}>
          <span style={{ color: check.status === "pass" ? "#22c55e" : check.status === "warn" ? "#eab308" : "#ef4444", flexShrink: 0 }}>
            {check.status === "pass" ? "[OK]" : check.status === "warn" ? "[!!]" : "[XX]"}
          </span>
          <span style={{ flex: 1, fontSize: 11, color: "#cccccc" }}>{check.label}</span>
          <span style={{ color: "#666666", fontSize: 10 }}>
            {check.points}/{check.maxPoints}
          </span>
        </div>
      ))}

      {score < 80 ? (
        <>
          <div style={dividerStyle} />
          <p style={{ margin: 0, color: "#888888", fontSize: 10 }}>
            Run npx agent-ready agent-ready to improve
          </p>
        </>
      ) : null}
    </div>
  );
}

function TestModeBadge() {
  return (
    <a
      href="https://github.com/waynesutton/agent-ready-component/blob/main/INTEGRATION.md#section-testmode--going-to-production"
      target="_blank"
      rel="noreferrer"
      style={{
        display: "inline-block",
        padding: "2px 8px",
        borderRadius: 3,
        border: "1px solid #8b5a00",
        background: "#2a1a00",
        color: "#ffb347",
        fontSize: 10,
        letterSpacing: "0.15em",
        textDecoration: "none",
        marginBottom: 8,
      }}
    >
      TEST MODE
    </a>
  );
}

// --- Styles ---

function positionStyle(position: WidgetPosition, isMobile: boolean): React.CSSProperties {
  // Tighter insets on mobile so the widget never collides with safe-area edges.
  const edge = isMobile ? 12 : 24;
  switch (position) {
    case "footer":
      return { position: "relative", margin: "24px auto" };
    case "floating-bottom-left":
      return { position: "fixed", bottom: edge, left: edge, zIndex: 9999 };
    case "floating-center":
      return {
        position: "fixed",
        bottom: edge,
        left: "50%",
        transform: "translateX(-50%)",
        zIndex: 9999,
      };
    case "floating-bottom-right":
    default:
      return { position: "fixed", bottom: edge, right: edge, zIndex: 9999 };
  }
}

const toggleRowStyle: React.CSSProperties = { display: "flex" };
const mobileToggleButtonStyle: React.CSSProperties = {
  flex: "0 0 auto",
  width: 40,
  height: 40,
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  background: "#111111",
  color: "var(--agent-ready-text-inactive, #888888)",
  border: "none",
  borderBottom: "1px solid var(--agent-ready-panel-border, #333333)",
  borderLeft: "1px solid var(--agent-ready-panel-border, #333333)",
  cursor: "pointer",
  padding: 0,
};
const panelStyle: React.CSSProperties = { padding: 12, display: "flex", flexDirection: "column", gap: 6 };
const paragraphStyle: React.CSSProperties = { margin: 0, fontWeight: 600 };
const subParagraphStyle: React.CSSProperties = { margin: 0, color: "#888888", fontSize: 11 };
const rowStyle: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 8,
};
const linkStyle: React.CSSProperties = {
  color: "var(--agent-ready-accent, #ffffff)",
  textDecoration: "none",
  fontSize: 12,
};
const copyButtonStyle: React.CSSProperties = {
  background: "transparent",
  color: "#888888",
  border: "1px solid #333333",
  borderRadius: 3,
  padding: "2px 8px",
  fontFamily: "inherit",
  fontSize: 10,
  letterSpacing: "0.1em",
  cursor: "pointer",
};
const iconLinkStyle: React.CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  padding: "2px 4px",
  borderRadius: 3,
  textDecoration: "none",
  cursor: "pointer",
  transition: "opacity 120ms ease",
};
const externalLinkStyle: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  gap: 8,
  color: "#888888",
  textDecoration: "none",
  fontSize: 11,
  padding: "3px 0",
  transition: "color 120ms ease",
};
const dividerStyle: React.CSSProperties = {
  height: 1,
  background: "var(--agent-ready-panel-border, #333333)",
  margin: "4px 0",
};
const scoreCheckRowStyle: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 6,
  fontSize: 11,
  fontFamily: "'Courier New', Courier, monospace",
};
const metaStyle: React.CSSProperties = { margin: "6px 0 0", color: "#666666", fontSize: 10 };
const staleBannerStyle: React.CSSProperties = {
  background: "#2a1a00",
  color: "#ffb347",
  border: "1px solid #8b5a00",
  borderRadius: 3,
  padding: "4px 8px",
  fontSize: 10,
  letterSpacing: "0.1em",
  marginBottom: 8,
};

// src/svelte/AgentReadyWidget.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { createAgentReadyStatusStore } from "./store.js";
  import type { AgentReadyStatus, ReadinessReport, WidgetColors, WidgetPosition, WidgetTheme } from "../client/types.js";

  export let appUrl: string;
  /**
   * Optional public app URL used for visible file links and AI chat prompts.
   * Set this when your production frontend lives on a different domain than the endpoint base.
   * Falls back to status.appUrl from the component, then window.location.origin, then appUrl.
   */
  export let publicAppUrl: string | undefined = undefined;
  export let position: WidgetPosition = "floating-bottom-right";
  export let theme: WidgetTheme = "system";
  // Hide the entire widget while keeping generated files and routes active.
  export let visible: boolean | undefined = undefined;
  export let showTestModeBadge: boolean = true;
  export let showStatus: boolean | undefined = undefined;
  export let showFiles: boolean | undefined = undefined;
  export let showAppName: boolean | undefined = undefined;
  export let showDescription: boolean | undefined = undefined;
  export let showMeta: boolean | undefined = undefined;
  export let showScoreTab: boolean | undefined = undefined;
  export let cleanMode: boolean | undefined = undefined;
  export let showHumanTab: boolean | undefined = undefined;
  export let showMachineTab: boolean | undefined = undefined;
  export let showChatLinks: boolean | undefined = undefined;
  export let showChatGPT: boolean | undefined = undefined;
  export let showClaude: boolean | undefined = undefined;
  export let showPerplexity: boolean | undefined = undefined;
  export let colors: Partial<WidgetColors> = {};
  export let llmsTxtPath: string = "/llms.txt";
  export let agentsMdPath: string = "/agents.md";
  export let fullTxtPath: string = "/llms-full.txt";
  export let statusPath: string = "/llms-status";
  export let readinessPath: string = "/llms-readiness";
  export let rssFeedPath: string = "/feed.xml";

  // Mobile collapse controls. Defaults preserve existing desktop behavior.
  export let mobileCollapse: boolean = true;
  export let mobileBreakpoint: number = 480;
  export let defaultMobileCollapsed: boolean = true;
  // Desktop collapse opt-in. Resolves from prop, then status.widgetDesktopCollapse, then true.
  export let desktopCollapse: boolean | undefined = undefined;

  type Tab = "HUMAN" | "MACHINE" | "SCORE";
  let tab: Tab = "HUMAN";

  // Mobile viewport detection via matchMedia. SSR safe: stays false on the server.
  let isMobile: boolean = false;
  let collapsed: boolean = defaultMobileCollapsed;
  let mql: MediaQueryList | null = null;
  function handleMediaChange(event: MediaQueryListEvent): void {
    isMobile = event.matches;
  }

  onMount(() => {
    if (typeof window === "undefined" || !window.matchMedia) return;
    mql = window.matchMedia(`(max-width: ${mobileBreakpoint}px)`);
    isMobile = mql.matches;
    if (mql.addEventListener) {
      mql.addEventListener("change", handleMediaChange);
    } else {
      mql.addListener(handleMediaChange);
    }
  });

  onDestroy(() => {
    if (!mql) return;
    if (mql.removeEventListener) {
      mql.removeEventListener("change", handleMediaChange);
    } else {
      mql.removeListener(handleMediaChange);
    }
  });

  // mobileActive drives mobile-specific visuals (width clamp, edge insets, compact tabs).
  $: mobileActive = isMobile && mobileCollapse;
  // desktopCollapseEnabled resolves prop > config > false. Active only off-mobile.
  $: desktopCollapseEnabled = desktopCollapse ?? currentStatus?.widgetDesktopCollapse ?? true;
  $: desktopCollapseActive = !isMobile && desktopCollapseEnabled;
  // collapseActive drives toggle button + panel visibility regardless of viewport.
  $: collapseActive = mobileActive || desktopCollapseActive;
  $: showPanel = !collapseActive || !collapsed;

  const status = createAgentReadyStatusStore({ appUrl, statusPath });
  let currentStatus: AgentReadyStatus | null = null;
  let initialVersion: string | null = null;
  let isStale = false;

  const unsubscribe = status.subscribe((value) => {
    currentStatus = value;
    if (value?.generatedFromVersion && initialVersion === null) {
      initialVersion = value.generatedFromVersion;
    }
    isStale =
      !!value?.generatedFromVersion &&
      !!initialVersion &&
      value.generatedFromVersion !== initialVersion;
  });

  onDestroy(() => unsubscribe());

  // Readiness report polling (60s interval, matches React hook)
  let readiness: ReadinessReport | null = null;
  let readinessInterval: ReturnType<typeof setInterval> | null = null;

  // Readiness endpoint always lives on the deployment that runs the component.
  $: readinessUrl = `${(appUrl || "").replace(/\/+$/, "")}${readinessPath}`;

  async function fetchReadiness(): Promise<void> {
    try {
      const res = await fetch(readinessUrl, { cache: "no-store" });
      if (!res.ok) return;
      readiness = (await res.json()) as ReadinessReport;
    } catch {
      // Degrade gracefully when endpoint unreachable.
    }
  }

  $: scoreTabVisible = showScoreTab ?? currentStatus?.widgetShowScoreTab ?? false;

  $: if (scoreTabVisible) {
    void fetchReadiness();
    if (!readinessInterval) {
      readinessInterval = setInterval(() => void fetchReadiness(), 60_000);
    }
  } else if (readinessInterval) {
    clearInterval(readinessInterval);
    readinessInterval = null;
  }

  onDestroy(() => {
    if (readinessInterval) clearInterval(readinessInterval);
  });

  // Score display helpers
  $: scoreDotColor =
    readiness
      ? readiness.score >= 80 ? "#22c55e" : readiness.score >= 50 ? "#eab308" : "#ef4444"
      : "#666666";

  // Props override config. When prop is undefined, fall back to status endpoint (config-driven).
  $: resolvedVisible = visible ?? currentStatus?.widgetVisible ?? true;
  $: resolvedShowStatus = showStatus ?? currentStatus?.widgetStatusVisible ?? true;
  $: resolvedShowFiles = showFiles ?? currentStatus?.widgetShowFiles ?? true;
  $: resolvedShowAppName = showAppName ?? currentStatus?.widgetShowAppName ?? true;
  $: resolvedShowDescription = showDescription ?? currentStatus?.widgetShowDescription ?? true;
  $: resolvedShowMeta = showMeta ?? currentStatus?.widgetShowMeta ?? true;
  $: resolvedCleanMode = cleanMode ?? currentStatus?.widgetCleanMode ?? false;
  $: resolvedHumanTab = showHumanTab ?? currentStatus?.widgetShowHumanTab ?? true;
  $: resolvedMachineTab = showMachineTab ?? currentStatus?.widgetShowMachineTab ?? true;
  $: resolvedChatLinks = showChatLinks ?? currentStatus?.widgetShowChatLinks ?? true;
  $: resolvedChatGPT = showChatGPT ?? currentStatus?.widgetShowChatGPT ?? true;
  $: resolvedClaude = showClaude ?? currentStatus?.widgetShowClaude ?? true;
  $: resolvedPerplexity = showPerplexity ?? currentStatus?.widgetShowPerplexity ?? true;

  $: effectiveShowAppName = resolvedCleanMode ? false : resolvedShowAppName;
  $: effectiveShowDescription = resolvedCleanMode ? false : resolvedShowDescription;

  $: anyTabVisible = resolvedVisible && (resolvedHumanTab || resolvedMachineTab || scoreTabVisible);

  // Endpoint base: where the widget fetches /llms-status and /llms-readiness.
  $: endpointBase = (appUrl || (typeof window !== "undefined" ? window.location.origin : "")).replace(
    /\/+$/,
    "",
  );

  // Visible base: shown to humans and AI agents in the file links and chat prompts.
  // Precedence: publicAppUrl prop -> status.appUrl -> window.location.origin -> appUrl.
  $: visibleBase = (() => {
    if (publicAppUrl && publicAppUrl.length > 0) return publicAppUrl.replace(/\/+$/, "");
    if (currentStatus?.appUrl) return currentStatus.appUrl.replace(/\/+$/, "");
    if (typeof window !== "undefined") return window.location.origin.replace(/\/+$/, "");
    return endpointBase;
  })();

  // Dev-only warning for the common Vite trap where a Convex .site URL leaks into prod.
  $: {
    if (typeof window !== "undefined" && visibleBase) {
      const isProd =
        typeof process !== "undefined" && process.env && process.env.NODE_ENV === "production";
      const origin = window.location.origin;
      const isLocal = /^(http:\/\/localhost|http:\/\/127\.0\.0\.1|http:\/\/\[::1\])/.test(origin);
      if (
        !isProd &&
        !isLocal &&
        visibleBase.includes(".convex.site") &&
        !origin.includes(".convex.site")
      ) {
        try {
          const sameHost = new URL(visibleBase).host === new URL(origin).host;
          if (!sameHost) {
            console.warn(
              "[agent-ready] Widget visible URL points to a Convex .site URL while the browser is on a custom domain. " +
                "Set publicAppUrl on <AgentReadyWidget> or VITE_SITE_URL in your build to avoid leaking the dev URL.",
            );
          }
        } catch {
          // ignore parse errors
        }
      }
    }
  }

  $: base = visibleBase;
  $: urls = {
    llmsTxt: `${visibleBase}${llmsTxtPath}`,
    agentsMd: `${visibleBase}${agentsMdPath}`,
    fullTxt: `${visibleBase}${fullTxtPath}`,
    rssFeed: `${visibleBase}${rssFeedPath}`,
    // Status link still points at the endpoint base because that is where the JSON lives.
    status: `${endpointBase}${statusPath}`,
  };

  $: encodedLlms = encodeURIComponent(urls.llmsTxt);
  $: chatLinks = {
    chatgpt: `https://chatgpt.com/?hints=search&q=Read+this+URL+${encodedLlms}+and+summarize+the+app`,
    claude: `https://claude.ai/new?q=Read+this+URL+${encodedLlms}+and+summarize+the+app`,
    perplexity: `https://www.perplexity.ai/?q=Read+this+URL+${encodedLlms}+and+summarize+the+app`,
  };

  function positionStyles(pos: WidgetPosition, mobile: boolean): string {
    // Tighter insets on mobile so the widget never collides with safe-area edges.
    const edge = mobile ? 12 : 24;
    if (pos === "footer") return "position: relative; margin: 24px auto;";
    if (pos === "floating-bottom-left") return `position: fixed; bottom: ${edge}px; left: ${edge}px; z-index: 9999;`;
    if (pos === "floating-center") return `position: fixed; bottom: ${edge}px; left: 50%; transform: translateX(-50%); z-index: 9999;`;
    return `position: fixed; bottom: ${edge}px; right: ${edge}px; z-index: 9999;`;
  }

  $: colorVarStyle = [
    colors.bg ? `--agent-ready-bg: ${colors.bg}` : "",
    colors.border ? `--agent-ready-panel-border: ${colors.border}` : "",
    colors.textActive ? `--agent-ready-text-active: ${colors.textActive}` : "",
    colors.textInactive ? `--agent-ready-text-inactive: ${colors.textInactive}` : "",
    colors.tabActiveBg ? `--agent-ready-tab-active-bg: ${colors.tabActiveBg}` : "",
    colors.accent ? `--agent-ready-accent: ${colors.accent}` : "",
  ].filter(Boolean).join("; ");

  $: widgetWidthStyle = mobileActive
    ? "width: min(280px, calc(100vw - 24px)); max-width: calc(100vw - 24px);"
    : "width: 280px;";

  $: widgetStyle = `${positionStyles(position, mobileActive)}; ${widgetWidthStyle}; ${colorVarStyle}`;

  async function copy(url: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(url);
    } catch {
      // Silent fail on permission denial.
    }
  }
</script>

{#if anyTabVisible}
<div class="widget" class:mobile={mobileActive} class:collapse-active={collapseActive} data-theme={theme} style={widgetStyle}>
  <div class="tabs">
    {#if resolvedHumanTab}
      <button class:active={tab === "HUMAN"} on:click={() => (tab = "HUMAN")}>HUMAN</button>
    {/if}
    {#if resolvedMachineTab}
      <button class:active={tab === "MACHINE"} on:click={() => (tab = "MACHINE")}>MACHINE</button>
    {/if}
    {#if scoreTabVisible}
      <button class:active={tab === "SCORE"} on:click={() => (tab = "SCORE")}>SCORE</button>
    {/if}
    {#if collapseActive}
      <button
        type="button"
        class="mobile-toggle"
        aria-expanded={!collapsed}
        aria-label={collapsed ? "Expand widget" : "Collapse widget"}
        on:click={() => (collapsed = !collapsed)}
      >
        {#if collapsed}
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="currentColor"><path d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"/></svg>
        {:else}
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="currentColor"><path d="M213.66,165.66a8,8,0,0,1-11.32,0L128,91.31,53.66,165.66a8,8,0,0,1-11.32-11.32l80-80a8,8,0,0,1,11.32,0l80,80A8,8,0,0,1,213.66,165.66Z"/></svg>
        {/if}
      </button>
    {/if}
  </div>

  {#if !showPanel}
    <!-- collapsed on mobile -->
  {:else if tab === "SCORE"}
    <div class="panel">
      {#if !readiness}
        <p class="meta" style="margin: 0;">Loading readiness...</p>
      {:else}
        <div class="score-header">
          <span class="score-dot" style="background: {scoreDotColor};"></span>
          <span class="score-value">{readiness.score}</span>
          <span class="score-label">/100</span>
        </div>

        <div class="divider"></div>

        <div class="checks-list">
          {#each readiness.checks as check (check.id)}
            <div class="check-row">
              <span class={check.status === "pass" ? "check-pass" : check.status === "warn" ? "check-warn" : "check-fail"}>
                {check.status === "pass" ? "[OK]" : check.status === "warn" ? "[!!]" : "[XX]"}
              </span>
              <span class="check-label">{check.label}</span>
              <span class="check-points">{check.points}/{check.maxPoints}</span>
            </div>
          {/each}
        </div>

        {#if readiness.score < 80}
          <div class="divider"></div>
          <p class="hint">Run npx agent-ready agent-ready to improve</p>
        {/if}
      {/if}
    </div>
  {:else if tab === "HUMAN"}
    <div class="panel">
      {#if effectiveShowAppName}
        <p class="title">{currentStatus?.appName ?? "LLMs discovery"}</p>
      {/if}
      {#if effectiveShowDescription}
        <p class="sub">These files help AI agents understand this app.</p>
      {/if}
      {#if resolvedShowFiles}
        <div class="row"><a href={urls.llmsTxt} target="_blank" rel="noreferrer">llms.txt</a><button on:click={() => copy(urls.llmsTxt)}>copy</button></div>
        <div class="row"><a href={urls.agentsMd} target="_blank" rel="noreferrer">agents.md</a><button on:click={() => copy(urls.agentsMd)}>copy</button></div>
        {#if currentStatus?.fullTxtEnabled}
          <div class="row"><a href={urls.fullTxt} target="_blank" rel="noreferrer">llms-full.txt</a><button on:click={() => copy(urls.fullTxt)}>copy</button></div>
        {/if}
        {#if currentStatus?.rssEnabled}
          <div class="row"><a href={urls.rssFeed} target="_blank" rel="noreferrer">feed.xml</a><button on:click={() => copy(urls.rssFeed)}>copy</button></div>
        {/if}
      {/if}
      {#if resolvedChatLinks}
        {#if effectiveShowAppName || effectiveShowDescription || resolvedShowFiles}
          <div class="divider"></div>
        {/if}
        {#if resolvedChatGPT}
          <a class="ext-link" href={chatLinks.chatgpt} target="_blank" rel="noreferrer">
            <span>Open in ChatGPT</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg>
          </a>
        {/if}
        {#if resolvedClaude}
          <a class="ext-link" href={chatLinks.claude} target="_blank" rel="noreferrer">
            <span>Open in Claude</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg>
          </a>
        {/if}
        {#if resolvedPerplexity}
          <a class="ext-link" href={chatLinks.perplexity} target="_blank" rel="noreferrer">
            <span>Open in Perplexity</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg>
          </a>
        {/if}
      {/if}
    </div>
  {:else}
    <div class="panel">
      {#if showTestModeBadge && currentStatus?.testMode}
        <a class="testmode-badge" href="https://github.com/waynesutton/agent-ready-component/blob/main/INTEGRATION.md#section-testmode--going-to-production" target="_blank" rel="noreferrer">TEST MODE</a>
      {/if}
      {#if isStale}
        <div class="stale" role="status" aria-live="polite">Content updated — refresh</div>
      {/if}
      <div class="row"><a href={urls.llmsTxt} target="_blank" rel="noreferrer">llms.txt</a><a class="icon-link" href={urls.llmsTxt} target="_blank" rel="noreferrer" title="Open llms.txt"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg></a></div>
      <div class="row"><a href={urls.agentsMd} target="_blank" rel="noreferrer">agents.md</a><a class="icon-link" href={urls.agentsMd} target="_blank" rel="noreferrer" title="Open agents.md"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg></a></div>
      {#if currentStatus?.fullTxtEnabled}
        <div class="row"><a href={urls.fullTxt} target="_blank" rel="noreferrer">llms-full.txt</a><a class="icon-link" href={urls.fullTxt} target="_blank" rel="noreferrer" title="Open llms-full.txt"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg></a></div>
      {/if}
      {#if currentStatus?.rssEnabled}
        <div class="row"><a href={urls.rssFeed} target="_blank" rel="noreferrer">feed.xml</a><a class="icon-link" href={urls.rssFeed} target="_blank" rel="noreferrer" title="Open RSS feed"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg></a></div>
      {/if}
      {#if resolvedShowStatus}
        <div class="row"><a href={urls.status} target="_blank" rel="noreferrer">status</a><a class="icon-link" href={urls.status} target="_blank" rel="noreferrer" title="Open status"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 256 256" fill="#888888"><path d="M224,104a8,8,0,0,1-16,0V59.31l-66.34,66.35a8,8,0,0,1-11.32-11.32L196.69,48H152a8,8,0,0,1,0-16h64a8,8,0,0,1,8,8Zm-40,24a8,8,0,0,0-8,8v72H48V80h72a8,8,0,0,0,0-16H48A16,16,0,0,0,32,80V208a16,16,0,0,0,16,16H176a16,16,0,0,0,16-16V136A8,8,0,0,0,184,128Z"/></svg></a></div>
      {/if}
      {#if resolvedShowMeta}
        <p class="meta">
          {#if currentStatus?.lastGeneratedAt}
            generated {new Date(currentStatus.lastGeneratedAt).toLocaleString()}
          {:else}
            not generated yet
          {/if}
        </p>
        {#if currentStatus?.generationInProgress}<p class="meta">Generating...</p>{/if}
        {#if currentStatus?.hasDrafts}<p class="meta">Drafts pending</p>{/if}
      {/if}
    </div>
  {/if}
</div>
{/if}

<style>
  .widget {
    width: 280px;
    background: var(--agent-ready-bg, #1a1a1a);
    border: 1px solid var(--agent-ready-panel-border, #333333);
    border-radius: var(--agent-ready-radius, 4px);
    color: var(--agent-ready-text-active, #e5e5e5);
    font-family: var(--agent-ready-font, "Courier New", Courier, monospace);
    font-size: 12px;
    letter-spacing: 0.1em;
    overflow: hidden;
  }
  .tabs {
    display: flex;
  }
  .tabs button {
    flex: 1;
    height: 40px;
    min-width: 100px;
    background: #111111;
    color: var(--agent-ready-text-inactive, #666666);
    font: inherit;
    letter-spacing: inherit;
    border: none;
    border-bottom: 1px solid var(--agent-ready-panel-border, #333333);
    cursor: pointer;
    transition: background 120ms ease;
  }
  .tabs button.active {
    background: var(--agent-ready-tab-active-bg, #2a2a2a);
    color: var(--agent-ready-text-active, #e5e5e5);
    font-weight: 600;
  }
  .tabs button.mobile-toggle {
    flex: 0 0 auto;
    width: 40px;
    min-width: 0;
    padding: 0;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-left: 1px solid var(--agent-ready-panel-border, #333333);
    color: var(--agent-ready-text-inactive, #888888);
  }
  /* When the caret toggle is shown (mobile collapse or desktop collapse), let the
     HUMAN/MACHINE/SCORE tabs shrink so the toggle still fits inside 280px. */
  .widget.collapse-active .tabs button {
    min-width: 0;
  }
  .panel {
    padding: 12px;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .title {
    margin: 0;
    font-weight: 600;
  }
  .sub {
    margin: 0;
    color: #888888;
    font-size: 11px;
  }
  .row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 8px;
  }
  .row a {
    color: var(--agent-ready-accent, #ffffff);
    text-decoration: none;
    font-size: 12px;
  }
  .row button {
    background: transparent;
    color: #888888;
    border: 1px solid #333333;
    border-radius: 3px;
    padding: 2px 8px;
    font: inherit;
    font-size: 10px;
    letter-spacing: 0.1em;
    cursor: pointer;
  }
  .icon-link {
    display: inline-flex;
    align-items: center;
    padding: 2px 4px;
    border-radius: 3px;
    text-decoration: none;
    cursor: pointer;
    transition: opacity 120ms ease;
  }
  .icon-link:hover {
    opacity: 0.7;
  }
  .divider {
    height: 1px;
    background: var(--agent-ready-panel-border, #333333);
    margin: 4px 0;
  }
  .ext-link {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 8px;
    color: #888888;
    text-decoration: none;
    font-size: 11px;
    padding: 3px 0;
    transition: color 120ms ease;
  }
  .ext-link:hover {
    color: var(--agent-ready-text-active, #e5e5e5);
  }
  .meta {
    margin: 6px 0 0;
    color: #666666;
    font-size: 10px;
  }
  .testmode-badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 3px;
    border: 1px solid #8b5a00;
    background: #2a1a00;
    color: #ffb347;
    font-size: 10px;
    letter-spacing: 0.15em;
    text-decoration: none;
    margin-bottom: 8px;
    width: fit-content;
  }
  .stale {
    background: #2a1a00;
    color: #ffb347;
    border: 1px solid #8b5a00;
    border-radius: 3px;
    padding: 4px 8px;
    font-size: 10px;
    letter-spacing: 0.1em;
    margin-bottom: 8px;
  }
  .score-header {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 24px;
    font-weight: 700;
    margin-bottom: 4px;
  }
  .score-dot {
    display: inline-block;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .score-value {
    font-family: "Courier New", Courier, monospace;
    font-size: 24px;
    font-weight: 700;
    line-height: 1;
  }
  .score-label {
    color: #888888;
    font-size: 11px;
    font-weight: 400;
  }
  .checks-list {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 10px;
    color: #888888;
  }
  .check-row {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 11px;
    font-family: "Courier New", Courier, monospace;
  }
  .check-pass {
    color: #22c55e;
    flex-shrink: 0;
  }
  .check-fail {
    color: #ef4444;
    flex-shrink: 0;
  }
  .check-warn {
    color: #eab308;
    flex-shrink: 0;
  }
  .check-label {
    flex: 1;
    font-size: 11px;
    color: #cccccc;
  }
  .check-points {
    color: #666666;
    font-size: 10px;
  }
  .hint {
    margin: 0;
    color: #888888;
    font-size: 10px;
  }
</style>
