// example-svelte/src/routes/settings/+page.svelte
<script lang="ts">
  import { useConvexClient, useQuery } from "convex-svelte";
  import { api } from "../../../convex/_generated/api";

  const client = useConvexClient();
  const status = useQuery(api.agentReady.content.getCacheStatus, {});
  const pages = useQuery(api.agentReady.content.listPages, { includeAllStatuses: true });

  let busy = $state(false);
  let tab = $state("pages");
  const tabs = [
    { id: "pages", label: "Pages" },
    { id: "cache", label: "Cache" },
    { id: "actions", label: "Actions" },
  ];

  async function regenerate() {
    busy = true;
    try {
      await client.action(api.agentReady.content.regenerateAll, {});
    } finally {
      busy = false;
    }
  }

  async function rollback(fileType: string) {
    await client.mutation(api.agentReady.content.rollbackCache, { fileType });
  }

  async function publish(path: string) { await client.mutation(api.agentReady.content.publishPage, { path }); }
  async function draft(path: string) { await client.mutation(api.agentReady.content.draftPage, { path }); }
  async function archive(path: string) { await client.mutation(api.agentReady.content.archivePage, { path }); }
</script>

<div class="hero">
  <h1>Settings</h1>
  <p class="lede">
    Control publish state, regenerate files, roll back to previous cache versions, and watch the
    live status stream.
  </p>
</div>

<div class="tabs" role="tablist">
  {#each tabs as t}
    <button
      class="tab {tab === t.id ? 'active' : ''}"
      role="tab"
      aria-selected={tab === t.id}
      onclick={() => (tab = t.id)}
    >{t.label}</button>
  {/each}
</div>

{#if tab === "pages"}
  <h3>Pages</h3>
  {#if $pages}
    <table class="pages-table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Path</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#each $pages as page}
          <tr>
            <td style="font-weight: 600;">{page.title}</td>
            <td><code>{page.path}</code></td>
            <td><span class="pill {page.status}">{page.status}</span></td>
            <td class="actions">
              <button onclick={() => publish(page.path)}>Publish</button>
              <button onclick={() => draft(page.path)}>Draft</button>
              <button onclick={() => archive(page.path)}>Archive</button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
{/if}

{#if tab === "cache"}
  <h3>Live status</h3>
  {#if $status}
    <pre class="status-block">{JSON.stringify($status, null, 2)}</pre>
  {:else}
    <p style="color: var(--muted);">Loading status...</p>
  {/if}
{/if}

{#if tab === "actions"}
  <div class="settings-row">
    <button class="btn btn-primary" onclick={regenerate} disabled={busy}>
      {busy ? "Regenerating..." : "Regenerate all files"}
    </button>
    <button class="btn btn-ghost" onclick={() => rollback("llms.txt")} disabled={busy}>Rollback llms.txt</button>
    <button class="btn btn-ghost" onclick={() => rollback("agents.md")} disabled={busy}>Rollback agents.md</button>
    <button class="btn btn-ghost" onclick={() => rollback("llms-full.txt")} disabled={busy}>Rollback llms-full.txt</button>
  </div>
  <div class="callout">
    <strong>Tip:</strong> Rollback swaps the active cache entry. The next sync or cron run
    replaces it again.
  </div>
{/if}

// example-react/src/Settings.tsx
import { useAction, useMutation, useQuery } from "convex/react";
import { useState } from "react";
import { api } from "../convex/_generated/api";
import { Button } from "./components/Button";
import { Tabs } from "./components/Tabs";

type PageStatus = "published" | "draft" | "archived";

export default function Settings() {
  const status = useQuery(api.agentReady.content.getCacheStatus, {});
  const pages = useQuery(api.agentReady.content.listPages, { includeAllStatuses: true });
  const regenerate = useAction(api.agentReady.content.regenerateAll);
  const rollback = useMutation(api.agentReady.content.rollbackCache);
  const publishPage = useMutation(api.agentReady.content.publishPage);
  const draftPage = useMutation(api.agentReady.content.draftPage);
  const archivePage = useMutation(api.agentReady.content.archivePage);

  const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState("pages");
  const tabs = [
    { id: "pages", label: "Pages" },
    { id: "cache", label: "Cache" },
    { id: "actions", label: "Actions" },
  ];

  const onRegenerate = async () => {
    setBusy(true);
    try {
      await regenerate({});
    } finally {
      setBusy(false);
    }
  };

  return (
    <div>
      <div className="hero">
        <h1>Settings</h1>
        <p className="lede">
          Control publish state, regenerate files, roll back to previous cache versions, and watch
          the live status stream.
        </p>
      </div>

      <Tabs tabs={tabs} activeId={tab} onChange={setTab} />

      {tab === "pages" && (
        <div>
          <h3>Pages</h3>
          <table className="pages-table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Path</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {(pages ?? []).map((page: { _id: string; title: string; path: string; status: PageStatus }) => (
                <tr key={page._id}>
                  <td style={{ fontWeight: 600 }}>{page.title}</td>
                  <td><code>{page.path}</code></td>
                  <td>
                    <span className={`pill ${page.status}`}>{page.status}</span>
                  </td>
                  <td className="actions">
                    <button type="button" onClick={() => publishPage({ path: page.path })}>Publish</button>
                    <button type="button" onClick={() => draftPage({ path: page.path })}>Draft</button>
                    <button type="button" onClick={() => archivePage({ path: page.path })}>Archive</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {tab === "cache" && (
        <div>
          <h3>Live status</h3>
          {status ? (
            <pre className="status-block">{JSON.stringify(status, null, 2)}</pre>
          ) : (
            <p style={{ color: "var(--muted)" }}>Loading status...</p>
          )}
        </div>
      )}

      {tab === "actions" && (
        <div>
          <div className="settings-row">
            <Button variant="primary" onClick={onRegenerate} disabled={busy}>
              {busy ? "Regenerating..." : "Regenerate all files"}
            </Button>
            <Button variant="ghost" onClick={() => rollback({ fileType: "llms.txt" })} disabled={busy}>
              Rollback llms.txt
            </Button>
            <Button variant="ghost" onClick={() => rollback({ fileType: "agents.md" })} disabled={busy}>
              Rollback agents.md
            </Button>
            <Button variant="ghost" onClick={() => rollback({ fileType: "llms-full.txt" })} disabled={busy}>
              Rollback llms-full.txt
            </Button>
          </div>
          <div className="callout">
            <strong>Tip:</strong> Rollback swaps the active cache entry. The next sync or cron run
            replaces it again.
          </div>
        </div>
      )}
    </div>
  );
}
